name: news_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  dio: ^5.5.0+1
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
